---
title: "Other Research Questions"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(tidyverse)
```

Import dataset
```{r}
combined_happiness = read.csv("./combined_happiness.csv") |>
  janitor::clean_names()
```


# Q1: Which country has the highest and lowest happiness score?
# 2015
```{r}
combined_happiness |>
  filter(year == "2015") |>
  arrange(desc(score)) |>
  ggplot(aes(x = reorder(country, -score), y = score)) +
  geom_bar(stat = "identity") +
  labs(title = "2015 World Happiness Score Rank", x = "Countries", y = "Happiness Score") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1, size = 4))
```

# 2016
```{r}
combined_happiness |>
  filter(year == "2016") |>
  arrange(desc(score)) |>
  ggplot(aes(x = reorder(country, -score), y = score)) +
  geom_bar(stat = "identity") +
  labs(title = "2015 World Happiness Score Rank", x = "Countries", y = "Happiness Score") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1, size = 4))
```
