---
title: "Six Happiness Indicator Scores "
date: "2023-11-24"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    social: menu
    source_code: embed
---

```{r global, include=FALSE}
# load library
library(shiny)
library(tidyverse)
library(plotly)
library(purrr)
library(ggplot2)
library(stringr)
library(maps)
library(magrittr)
library(rvest)
library(countrycode)
```

```{r}
# load data
hap_df = read_csv("./data/combined_happiness.csv")|>
  mutate(
    year = as.factor(year)
  )

regional_hap_df = hap_df|>
  group_by(region,year) |>
  summarise(
    average_gdp_per_capita = mean(gdp_per_capita, na.rm = TRUE),
    average_social_support = mean(social_support, na.rm = TRUE),
    average_health_life_expectancy = mean(health_life_expectancy, na.rm = TRUE),
    average_freedom_to_make_life_choices = mean(freedom_to_make_life_choices, na.rm = TRUE),
    average_perception_of_corruption = mean(perception_of_corruption, na.rm = TRUE),
    average_generosity = mean(generosity, na.rm = TRUE)
  )|>
  pivot_longer(
    average_gdp_per_capita:average_generosity,
    names_to ="factor",
    names_prefix = "average_",
    values_to = "average_score"
  )
```

```{r}
iso_codes = countrycode::codelist[, c("un.name.en", "iso3c")]
names(iso_codes) = c("Country", "ISO3")

world_data <- ggplot2::map_data('world')
world_data <- fortify(world_data)

hap_df['ISO3'] <- iso_codes$ISO3[match(hap_df$country, iso_codes$Country)]
world_data["ISO3"] <- iso_codes$ISO3[match(world_data$region, iso_codes$Country)]

hap_df = hap_df |>
  mutate(
    ISO3 = if_else(country == "United States", "USA", ISO3),
    ISO3 = if_else(country == "United Kingdom", "GBR", ISO3),
    ISO3 = if_else(country == "Venezuela", "VEN", ISO3),
    ISO3 = if_else(country == "Czech Republic", "CZE", ISO3),
    ISO3 = if_else(country == "Taiwan", "TWN", ISO3),
    ISO3 = if_else(country == "South Korea", "KOR", ISO3),
    ISO3 = if_else(country == "Bolivia", "BOL", ISO3),
    ISO3 = if_else(country == "Moldova", "MDA", ISO3),
    ISO3 = if_else(country == "Russia", "RUS", ISO3),
    ISO3 = if_else(country == "Hong Kong", "CHN", ISO3),
    ISO3 = if_else(country == "Vietnam", "VNM", ISO3),
    ISO3 = if_else(country == "Turkey", "TUR", ISO3),
    ISO3 = if_else(country == "Macedonia", "MKD", ISO3),
    ISO3 = if_else(country == "Laos", "LAO", ISO3),
    ISO3 = if_else(country == "Swaziland", "SWZ", ISO3),
    ISO3 = if_else(country == "Palestinian Territories", "PSE", ISO3),
    ISO3 = if_else(country == "Iran", "IRN", ISO3),
    ISO3 = if_else(country == "Congo (Kinshasa)", "COD", ISO3),
    ISO3 = if_else(country == "Congo (Brazzaville)", "COG", ISO3),
    ISO3 = if_else(country == "Tanzania", "TZA", ISO3),
    ISO3 = if_else(country == "Syria", "SYR", ISO3),
    ISO3 = if_else(country == "Puerto Rico", "PRI", ISO3)
  )|>
  mutate(country = recode(str_trim(country),
                         "United States" = "USA",
                         "United Kingdom" = "UK",
                         "Congo (Kinshasa)" = "Democratic Republic of the Congo",
                         "Congo (Brazzaville)" = "Republic of Congo"))

world_data = world_data|>
  mutate(country = region)|>
  select(-region)

worldjoin <- inner_join(world_data, hap_df, by = "country")

cleanup <- theme(
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank(),
  panel.background = element_rect(fill = "white"),
  plot.title = element_text(hjust = 0.5)
)
```

Inputs {.sidebar data-width=400}
-----------------------------------------------------------------------

```{r}
 selectInput(inputId = "indicator", label = h3("Happiness Indicator"), 
    choices = list(
      "GDP Per Captia" = "gdp_per_capita", 
      "Social Support" = "social_support", 
      "Healthy Life Expectancy" = "health_life_expectancy",
      "Freedom to Make Life Choices" = "freedom_to_make_life_choices",
      "Perception of Corruption" = "perception_of_corruption",
      "Generosity" = "generosity"
      ), 
    selected = 1)
```

Row {.tabset}
-----------------------------------------------------------------------
### World MAP
```{r}
renderPlot({
  ggplot(worldjoin, mapping = aes(
    x=long,
    y=lat,
    group=group)) +
  scale_fill_viridis_c(option = "C") +
  coord_fixed(1.3) +
  geom_polygon(aes(fill=!!sym(input$indicator))) +
  cleanup
  })
```


Row {.tabset}
-----------------------------------------------------------------------

### Country Level Comparison
    
```{r}
renderPlotly({
  hap_df %>%
    mutate(country = fct_reorder(country, !!sym(input$indicator))) %>%
    plot_ly(
      x = ~country,
      y = ~get(input$indicator),
      color = ~year,
      type = 'bar',
      colors = 'viridis'
    ) %>%
    layout(
        xaxis = list(
          title = "country",
          tickfont = list(size = 6)
      ),
      yaxis = list(title = "Score")
    )
})
```

### Region Level Comparison

```{r}
renderPlotly({

  hap_df |>
  mutate(region = fct_reorder(region, !!sym(input$indicator)))|>
  group_by(region, year)|>
  summarise(
    average = mean(!!sym(input$indicator), na.rm = TRUE)
  ) |>
  plot_ly (
  x = ~region, y = ~average, color = ~year,
  type = "bar", colors = "viridis") |>
  layout(
    xaxis = list(title = "Region"),
    yaxis = list(title = "Average Score")
  )
  
})
```    

### Region Level Trend

```{r}
data = reactive({ 
  regional_hap_df |>
  filter(factor == input$indicator) 
})

renderPlotly({
  data()|>
  plot_ly(
      x = ~year, y = ~average_score, color = ~region,
      mode = 'lines+markers', type = 'scatter', colors = 'viridis',
      name = ~region) |>
    layout(
      xaxis = list(title = "Year"),
      yaxis = list(title = "Average Score")
    )
  
})
```

    